runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: buy-and-sell-7f9b2:us-central1:buy-and-sell-db
env_variables:
  DB_USER: hapi-server
  DB_PASS: 0014
  DB_NAME: buy-and-sell
  DB_SOCKET: /cloudsql/buy-and-sell-7f9b2:us-central1:buy-and-sell-db